services:
  db:
    container_name: db
    image: postgres:16
    network_mode: "host"
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./files:/files

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    network_mode: "host"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_working_dir:/var/lib/pgadmin
      - ./files:/files

volumes:
  pgadmin_working_dir:
    driver: local
  postgresql_data:
    driver: local